apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: waas-charts
  namespace: kwaf
spec:
  url: https://artifactory.devops.telekom.de/artifactory/dtt-taomy-taomy07-dev-helm/
  interval: 1m
  secretRef:
    name: helm-repo-cred
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: waas
  namespace: kwaf
spec:
  # serviceAccountName: m2m-sa
  interval: 1m
  chart:
    spec:
      chart: waas
      version: "1.22.0"
      sourceRef:
        kind: HelmRepository
        name: waas-charts
        namespace: kwaf
  #values:
