apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name: bwapp-sample
  namespace: test
  labels:
    release: waas
spec:
  policies:
  - name: bwapp-policy
    operatorEmail: support@radware.com
    protections:
    - id: bwapp
      signatures:
        opMode: Active
      expressions:
        opMode: Active
    classifiers:
    - protectionId: bwapp
      hostname: '*'
      id: bwapp-sample
      path:
        operand: Prefix
        value: /